server:
  port: "11050"
  success_url: "https://riseoftheblacksun.eu/pay_success"
  fail_url: "https://riseoftheblacksun.eu/pay_error"

tinkoff:
  terminal_key: "XXXXXX"
  secret_key: "XXXXXXXX"
  notification_url: "https://shopservice.riseoftheblacksun.eu/notify"
  default_taxation: "osn"   # значение системы налогообложения для всех товаров
database:
  dialect: "sqlite3"       # или "postgres"
  connection: "test.db"      # для postgres укажите connection string

cors:
  allowed_origins:
    - "https://riseoftheblacksun.eu"
    - "riseoftheblacksun.eu"
external_service:
  domain: "https://shopservice.riseoftheblacksun.eu/api/process"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "purchase-event"
