server:
  port: "8080"
  success_url: "https://bosinn.world/pay_success"
  fail_url: "https://bosinn.world/pay_errored"

tinkoff:
  terminal_key: ""
  secret_key: ""
  notification_url: "https://payment.bosinn.world/notify"
  default_taxation: "osn"   # значение системы налогообложения для всех товаров
database:
  dialect: "sqlite3"       # или "postgres"
  connection: "test.db"      # для postgres укажи connection string

cors:
  allowed_origins:
    - "https://riseoftheblacksun.eu"
    - "riseoftheblacksun.eu"
    - "*"
