# config.yaml (рядом с main.go)

server:
  port: "8080"
  success_url: "https://example.com/success"
  fail_url: "https://example.com/fail"

tinkoff:
  terminal_key: "YOUR_TERMINAL_KEY"
  secret_key: "YOUR_SECRET_KEY"
  notification_url: "https://yourdomain.com/notify"

database:
  dialect: "sqlite3"
  connection: "payments.db"

cors:
  allowed_origins:
    - "*"

rcon:
  address: "127.0.0.1:25575"
  password: "minecraft_rcon_password"
  command: "op {player}"
