name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Устанавливаем Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      # 2) Инициализируем go.mod/go.sum прямо в корне репозитория
      - name: Initialize Go module
        run: |
          # если go.mod ещё нет — инициализируем модуль
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ github.repository }}
          fi
          go mod tidy

      # 3) Собираем Docker-образ из корня
      - name: Build the Docker image
        run: |
          docker build \
            -f Dockerfile \
            -t my-image-name:$(date +%s) \
            .
